[package]
name = "sctui"
version = "0.1.0"
description = "a soundcloud client for the terminal"
authors = ["Will Murphy <illogicallledits@gmail.com>"]
license = "MIT"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
ratatui = "0.29.0"
color-eyre = "0.6.3"
anyhow = "1"
base64 = "0.22"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
sha2 = "0.10"
tiny_http = "0.12"
webbrowser = "1.0"
reqwest = { version = "0.12", features = ["blocking", "json"] }
serde_json = "1.0.149"
chrono = { version = "0.4", features = ["serde"] }
tokio = {version = "1.47.1", features = ["rt-multi-thread"] }
rodio = "0.21.1"
ratatui-image = "8.0.1"
image = "0.25.9"
m3u8-rs = "6.0"
rustfft = "6.4.1"
